import { Background, ReactFlow, type Edge, type Node } from '@xyflow/react'
import '@xyflow/react/dist/style.css'
import { useEffect, useState } from 'react'
import { Button } from '../../components/Button'
import { Card } from '../../components/Card'
import { StatusBadge } from '../../components/StatusBadge'
import { OperatorLayout } from '../../layouts/OperatorLayout'
import { approveRecovery, editRecoveryPlan, getOperatorDisruptions, rejectRecovery, subscribeToOperatorUpdates, type OperatorDisruption } from '../../services/operatorService'
import { apiRequest } from '../../services/apiClient'

type LiveAlert = { id: string; tripId: string; userId: string; lat: number | null; lng: number | null; message: string | null; status: 'OPEN'|'ACKNOWLEDGED'|'RESOLVED'; createdAt: string; resolvedAt: string | null; user: { name: string; email: string }; trip: { id: string; destination: string; user: { name: string } }; itineraryItem: { id: string; title: string } | null }
export function OperatorDisruptionsPage() {
  const [disruptions, setDisruptions] = useState<OperatorDisruption[]>([]); const [selected, setSelected] = useState<string | null>(null); const [alerts, setAlerts] = useState<LiveAlert[]>([]); const [error, setError] = useState(''); const [working, setWorking] = useState<string | null>(null)
  const loadAlerts = () => { void apiRequest<{ alerts: LiveAlert[] }>('/operator/sos-alerts').then((result) => setAlerts(result.alerts)).catch((reason) => setError(reason instanceof Error ? reason.message : 'Live alerts are unavailable.')) }
  useEffect(() => { const load = () => { void getOperatorDisruptions().then((next) => { setDisruptions(next); setSelected((current) => current && next.some((item) => item.id === current) ? current : next[0]?.id || null) }).catch((reason) => setError(reason instanceof Error ? reason.message : 'Disruption console is unavailable.')) }; load(); loadAlerts(); return subscribeToOperatorUpdates(() => { load(); loadAlerts() }) }, [])
  const updateAlert = async (id: string, status: 'ACKNOWLEDGED'|'RESOLVED', tripId: string) => { try { setWorking(id); await apiRequest(`/trips/${tripId}/sos/${id}`, { method: 'PATCH', body: JSON.stringify({ status }) }); await loadAlerts() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to update SOS alert.') } finally { setWorking(null) } }
  const disruption = disruptions.find((item) => item.id === selected) || disruptions[0]
  const decide = async (planId: string, action: 'approve' | 'reject') => { try { setWorking(planId); if (action === 'approve') await approveRecovery(planId); else await rejectRecovery(planId); setDisruptions(await getOperatorDisruptions()) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to update the recovery plan.') } finally { setWorking(null) } }
  const edit = async (planId: string, current: string) => { const explanation = window.prompt('Update recovery plan explanation', current); if (!explanation) return; try { setWorking(planId); await editRecoveryPlan(planId, explanation); setDisruptions(await getOperatorDisruptions()) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to edit the recovery plan.') } finally { setWorking(null) } }
  const nodes: Node[] = (disruption?.nodes || []).map((node) => ({ ...node, className: `operator-flow-node ${node.id === disruption?.affectedItem.id ? 'is-critical' : ''}` })); const edges: Edge[] = (disruption?.edges || []).map((edge) => ({ ...edge, className: 'operator-flow-edge' })); const planStatusLabel = (status: string) => status === 'PROPOSED' ? 'Awaiting traveler' : status === 'TRAVELER_APPROVED' ? 'Awaiting your approval' : status === 'APPROVED' ? 'Approved' : status === 'REJECTED' ? 'Rejected' : status
  return <OperatorLayout><section className="operator-page"><header className="operator-page-heading"><div><p className="eyebrow">Disruption + safety console</p><h1>{disruption ? `${disruption.affectedItem.title} impact.` : 'No disruptions open.'}</h1><p>{disruption ? `${disruption.trip.traveler} · ${disruption.trip.destination} · ${disruption.details}` : 'New traveler disruptions and safety alerts appear here automatically.'}</p></div><span className="operator-risk-live">{alerts.filter((a) => a.status === 'OPEN').length} live SOS</span></header>{error && <p className="auth-error">{error}</p>}
    <section className="operator-live-alerts"><div className="operator-section-heading"><div><p className="eyebrow">Safety assist</p><h2>Live Alerts</h2></div><span>{alerts.filter((a) => a.status !== 'RESOLVED').length} active</span></div><div className="operator-alert-list">{alerts.filter((a) => a.status !== 'RESOLVED').length === 0 && <Card><p className="page-copy">No open SOS alerts.</p></Card>}{alerts.filter((a) => a.status !== 'RESOLVED').map((alert) => <Card className="operator-alert-card" key={alert.id}><div><StatusBadge status={alert.status === 'OPEN' ? 'cancelled' : 'confirmed'} /><span>{new Date(alert.createdAt).toLocaleString()}</span></div><h3>{alert.trip.user.name} · {alert.trip.destination}</h3><p>{alert.message || 'Traveler requested urgent assistance.'}{alert.itineraryItem ? ` · ${alert.itineraryItem.title}` : ''}</p>{alert.lat !== null && alert.lng !== null && <small>Location: {alert.lat.toFixed(5)}, {alert.lng.toFixed(5)}</small>}<div><Button disabled={working !== null || alert.status !== 'OPEN'} onClick={() => void updateAlert(alert.id, 'ACKNOWLEDGED', alert.tripId)} type="button">{working === alert.id ? 'Updating…' : 'Acknowledge'}</Button><Button disabled={working !== null} onClick={() => void updateAlert(alert.id, 'RESOLVED', alert.tripId)} type="button" variant="secondary">Resolve</Button></div></Card>)}</div></section>
    {disruptions.length > 1 && <div className="copilot-suggestions">{disruptions.map((item) => <button key={item.id} onClick={() => setSelected(item.id)} type="button">{item.trip.traveler} · {item.affectedItem.title}</button>)}</div>}{disruption && <><div className="operator-disruption-grid"><Card className="operator-graph-card"><div className="operator-graph"><ReactFlow edges={edges} fitView nodes={nodes}><Background color="var(--tp-border)" gap={18} /></ReactFlow></div><p>Dependency graph from the traveler’s live itinerary. The marked node started this impact chain.</p></Card><aside className="operator-impact-summary"><Card><span>Affected components</span><strong>{nodes.length}</strong><small>{disruption.trip.traveler}'s trip</small></Card><Card><span>Recovery plans</span><strong>{disruption.plans.length}</strong><small>{disruption.severity} severity</small></Card></aside></div><section className="operator-plans"><div className="operator-section-heading"><div><p className="eyebrow">Recovery options</p><h2>Use the traveler’s same recovery plans.</h2></div></div><div>{disruption.plans.map((plan, index) => <Card className={`operator-plan ${plan.status === 'APPROVED' ? 'is-selected' : ''}`} key={plan.id}><span>#{index + 1} · {plan.finalScore} score · {planStatusLabel(plan.status)}</span><h3>{index === 0 ? 'Best deterministic match' : index === 1 ? 'Balanced alternative' : 'Verified fallback'}</h3><p>{plan.explanation}</p><strong>{plan.extraCost >= 0 ? '+' : ''}₹{plan.extraCost.toLocaleString()} · +{plan.timeDelta} min · {plan.preferenceScore}% match · {plan.vendorReliability}% reliable</strong><div><Button disabled={working !== null || plan.status !== 'PROPOSED'} onClick={() => void edit(plan.id, plan.explanation)} type="button" variant="ghost">Edit</Button><Button disabled={working !== null || plan.status !== 'TRAVELER_APPROVED'} onClick={() => void decide(plan.id, 'approve')} type="button">Approve</Button><Button disabled={working !== null || (plan.status !== 'PROPOSED' && plan.status !== 'TRAVELER_APPROVED')} onClick={() => void decide(plan.id, 'reject')} type="button" variant="secondary">Reject</Button></div></Card>)}</div></section></>}</section></OperatorLayout>
}
