import { useEffect, useMemo, useState } from 'react'
import { Button } from '../../components/Button'
import { Card } from '../../components/Card'
import { Input } from '../../components/Input'
import { Modal } from '../../components/Modal'
import { OperatorLayout } from '../../layouts/OperatorLayout'
import { assignTripCoordinator, createOperatorInventory, deleteOperatorInventory, getOperatorCustomers, getOperatorCoordinators, getOperatorInventory, getOperatorSchedule, getOperatorTrips, getVendors, updateOperatorInventory, updateOperatorItineraryItem, type OperatorCoordinator, type OperatorCustomer, type OperatorInventory, type OperatorScheduleItem, type OperatorTrip, type Vendor } from '../../services/operatorService'

type ResourceTab = 'Customers' | 'Hotels' | 'Transport' | 'Activities' | 'Coordinators' | 'Schedule'
const tabs: ResourceTab[] = ['Customers', 'Hotels', 'Transport', 'Activities', 'Coordinators', 'Schedule']
const inventoryType: Partial<Record<ResourceTab, OperatorInventory['type'][]>> = { Hotels: ['HOTEL'], Transport: ['FLIGHT', 'TRANSFER'], Activities: ['ACTIVITY'] }
const formatDate = (value: string) => new Date(value).toLocaleDateString(undefined, { day: 'numeric', month: 'short', year: 'numeric' })

export function OperatorResourcesPage() {
  const [tab, setTab] = useState<ResourceTab>('Customers')
  const [customers, setCustomers] = useState<OperatorCustomer[]>([])
  const [inventory, setInventory] = useState<OperatorInventory[]>([])
  const [coordinators, setCoordinators] = useState<OperatorCoordinator[]>([])
  const [schedule, setSchedule] = useState<OperatorScheduleItem[]>([])
  const [trips, setTrips] = useState<OperatorTrip[]>([])
  const [vendors, setVendors] = useState<Vendor[]>([])
  const [search, setSearch] = useState('')
  const [error, setError] = useState('')
  const [notice, setNotice] = useState('')
  const [busyId, setBusyId] = useState('')
  const [formOpen, setFormOpen] = useState(false)
  const [editingInventory, setEditingInventory] = useState<OperatorInventory | null>(null)
  const [editing, setEditing] = useState<OperatorScheduleItem | null>(null)
  const [scheduleForm, setScheduleForm] = useState({ title: '', location: '', startTime: '', endTime: '' })
  const [form, setForm] = useState({ vendorId: '', type: 'HOTEL' as OperatorInventory['type'], title: '', location: '', price: '', availability: 'Available', tags: '', details: '' })

  const load = async () => {
    setError('')
    try {
      const [nextCustomers, nextInventory, nextCoordinators, nextSchedule, tripData, nextVendors] = await Promise.all([getOperatorCustomers(), getOperatorInventory(), getOperatorCoordinators(), getOperatorSchedule(), getOperatorTrips(), getVendors()])
      setCustomers(nextCustomers); setInventory(nextInventory); setCoordinators(nextCoordinators); setSchedule(nextSchedule); setTrips(tripData.trips); setVendors(nextVendors)
    } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to load operations resources.') }
  }
  useEffect(() => { void load() }, [])

  const filteredCustomers = useMemo(() => customers.filter((item) => `${item.name} ${item.email} ${item.phone || ''} ${item.trips.map((trip) => trip.destination).join(' ')}`.toLowerCase().includes(search.toLowerCase())), [customers, search])
  const filteredInventory = useMemo(() => inventory.filter((item) => (!inventoryType[tab] || inventoryType[tab]!.includes(item.type)) && `${item.title} ${item.location} ${item.vendor.name} ${item.availability}`.toLowerCase().includes(search.toLowerCase())), [inventory, search, tab])
  const filteredSchedule = useMemo(() => schedule.filter((item) => `${item.title} ${item.destination} ${item.traveler.name} ${item.location} ${item.vendor?.name || ''}`.toLowerCase().includes(search.toLowerCase())), [schedule, search])
  const filteredCoordinators = useMemo(() => coordinators.filter((item) => `${item.name} ${item.email} ${item.phone || ''}`.toLowerCase().includes(search.toLowerCase())), [coordinators, search])
  const saveInventory = async () => {
    const price = Number(form.price)
    if (!form.vendorId || !form.title.trim() || !form.location.trim() || !Number.isFinite(price) || price < 0) { setError('Select a vendor and enter a title, location, and valid price.'); return }
    let details: Record<string, unknown> | null = null
    if (form.details.trim()) { try { const parsed: unknown = JSON.parse(form.details); if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) throw new Error(); details = parsed as Record<string, unknown> } catch { setError('Service details must be a valid JSON object.'); return } }
    try { setBusyId(editingInventory?.id || 'create'); const input = { title: form.title.trim(), location: form.location.trim(), price, availability: form.availability.trim(), tags: form.tags.split(',').map((tag) => tag.trim()).filter(Boolean), details }; if (editingInventory) { await updateOperatorInventory(editingInventory.id, input); setNotice('Inventory details updated.') } else { await createOperatorInventory({ ...input, vendorId: form.vendorId, type: form.type }); setNotice('Inventory item added and available to trip planning.') } setFormOpen(false); setEditingInventory(null); setForm({ ...form, title: '', location: '', price: '', tags: '', details: '' }); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to save inventory.') } finally { setBusyId('') }
  }
  const toggleAvailability = async (item: OperatorInventory) => {
    const availability = item.bookable ? 'Unavailable' : 'Available'
    try { setBusyId(item.id); await updateOperatorInventory(item.id, { availability }); setInventory((rows) => rows.map((row) => row.id === item.id ? { ...row, availability, bookable: availability === 'Available' } : row)); setNotice(`${item.title} is now ${availability.toLowerCase()}.`) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to update availability.') } finally { setBusyId('') }
  }
  const editInventory = (item: OperatorInventory) => { setEditingInventory(item); setForm({ vendorId: item.vendorId, type: item.type, title: item.title, location: item.location, price: String(item.price), availability: item.availability, tags: Array.isArray(item.tags) ? item.tags.join(', ') : '', details: item.details ? JSON.stringify(item.details, null, 2) : '' }); setFormOpen(true); setError('') }
  const removeInventory = async (item: OperatorInventory) => { if (!window.confirm(`Delete ${item.title}? Services already attached to a tour must be marked unavailable instead.`)) return; try { setBusyId(item.id); await deleteOperatorInventory(item.id); setInventory((rows) => rows.filter((row) => row.id !== item.id)); setNotice(`${item.title} was deleted from inventory.`) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to delete inventory.'); } finally { setBusyId('') } }
  const assign = async (tripId: string, coordinatorId: string) => {
    try { setBusyId(tripId); await assignTripCoordinator(tripId, coordinatorId || null); setNotice('Coordinator assignment saved.'); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to assign coordinator.') } finally { setBusyId('') }
  }
  const openScheduleEdit = (item: OperatorScheduleItem) => { setEditing(item); setScheduleForm({ title: item.title, location: item.location, startTime: new Date(new Date(item.startTime).getTime() - new Date().getTimezoneOffset() * 60000).toISOString().slice(0, 16), endTime: new Date(new Date(item.endTime).getTime() - new Date().getTimezoneOffset() * 60000).toISOString().slice(0, 16) }); setError('') }
  const saveSchedule = async () => {
    if (!editing || !scheduleForm.title.trim() || !scheduleForm.location.trim() || !scheduleForm.startTime || !scheduleForm.endTime || new Date(scheduleForm.endTime) <= new Date(scheduleForm.startTime)) { setError('Enter a valid activity name, location, and end time after the start time.'); return }
    try { setBusyId(editing.id); await updateOperatorItineraryItem(editing.id, { title: scheduleForm.title.trim(), location: scheduleForm.location.trim(), startTime: new Date(scheduleForm.startTime).toISOString(), endTime: new Date(scheduleForm.endTime).toISOString() }); setEditing(null); setNotice('Schedule change saved. Conflicting time changes are rejected by the trip service.'); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to update schedule.') } finally { setBusyId('') }
  }

  return <OperatorLayout><section className="operator-page"><header className="operator-page-heading"><div><p className="eyebrow">Operations workspace</p><h1>Customers, resources & schedules.</h1><p>Manage traveler records, service inventory, coordinator assignments, and tour schedules in one place.</p></div></header>
    <div className="resource-tabs" role="tablist">{tabs.map((item) => <button aria-selected={tab === item} className={tab === item ? 'is-active' : ''} key={item} onClick={() => { setTab(item); setSearch(''); setError(''); setNotice('') }} role="tab" type="button">{item}</button>)}</div>
    {tab !== 'Coordinators' && <div className="resource-toolbar"><Input aria-label={`Search ${tab.toLowerCase()}`} onChange={(event) => setSearch(event.target.value)} placeholder={`Search ${tab.toLowerCase()}…`} value={search} />{inventoryType[tab] && <Button onClick={() => { setEditingInventory(null); setForm({ vendorId: '', type: tab === 'Transport' ? 'TRANSFER' : inventoryType[tab]![0], title: '', location: '', price: '', availability: 'Available', tags: '', details: '' }); setFormOpen(true); setError('') }} type="button">Add {tab.slice(0, -1)} inventory</Button>}</div>}
    {error && <p className="auth-error" role="alert">{error}</p>}{notice && <p className="auth-inline-message" role="status">{notice}</p>}
    {tab === 'Customers' && <Card className="operator-table-card"><h2>Traveler accounts</h2><div className="resource-table"><div className="resource-row resource-head"><span>Customer</span><span>Contact</span><span>Trips</span><span>Latest journey</span></div>{filteredCustomers.map((customer) => { const trip = customer.trips[0]; return <div className="resource-row" key={customer.id}><strong>{customer.name}</strong><span>{customer.email}{customer.phone ? ` · ${customer.phone}` : ''}</span><span>{customer.trips.length} · {customer.trips.reduce((sum, item) => sum + item.bookedItems, 0)} booked items</span><span>{trip ? `${trip.destination} · ${trip.status} · ₹${trip.budget.toLocaleString()}` : 'No trips yet'}</span></div> })}{filteredCustomers.length === 0 && <p className="page-copy">No customers match this search.</p>}</div></Card>}
    {inventoryType[tab] && <Card className="operator-table-card"><h2>{tab} inventory <small> · inventory is shared with itinerary recommendations</small></h2><div className="resource-table"><div className="resource-row resource-head"><span>Service</span><span>Vendor</span><span>Location</span><span>Price</span><span>Availability</span><span>Actions</span></div>{filteredInventory.map((item) => <div className="resource-row" key={item.id}><strong>{item.title} <small>{item.type}{item.details ? ` · ${JSON.stringify(item.details)}` : ''}</small></strong><span>{item.vendor.name}</span><span>{item.location}</span><span>₹{item.price.toLocaleString()}</span><span>{item.availability}{item.tags.length ? ` · ${item.tags.join(', ')}` : ''}</span><div className="resource-actions"><Button disabled={busyId === item.id} onClick={() => editInventory(item)} type="button" variant="secondary">Edit</Button><Button disabled={busyId === item.id} onClick={() => void toggleAvailability(item)} type="button" variant="ghost">{item.bookable ? 'Disable' : 'Enable'}</Button><Button disabled={busyId === item.id} onClick={() => void removeInventory(item)} type="button" variant="ghost">Delete</Button></div></div>)}{filteredInventory.length === 0 && <p className="page-copy">No inventory matches this search. Add a service to make it available to planners.</p>}</div></Card>}
    {tab === 'Coordinators' && <><Card className="operator-table-card"><h2>Coordinator directory</h2><div className="resource-table"><div className="resource-row resource-head"><span>Coordinator</span><span>Email</span><span>Phone</span><span>Assigned tours</span></div>{filteredCoordinators.map((person) => <div className="resource-row" key={person.id}><strong>{person.name}</strong><span>{person.email}</span><span>{person.phone || person.supportPhone || '—'}</span><span>{person.assignedTours}</span></div>)}{filteredCoordinators.length === 0 && <p className="page-copy">No coordinator accounts yet. Register an account with the Coordinator role first.</p>}</div></Card><Card className="operator-table-card"><h2>Assign a coordinator to a tour</h2><div className="resource-table">{trips.map((trip) => <div className="resource-row resource-assignment" key={trip.id}><span><strong>{trip.destination}</strong><small>{trip.traveler.name} · {trip.id.slice(-8)}</small></span><span>{trip.traveler.email}</span><select aria-label={`Coordinator for ${trip.destination}`} disabled={busyId === trip.id} onChange={(event) => void assign(trip.id, event.target.value)} value={trip.coordinatorId || ''}><option value="">Unassigned</option>{coordinators.map((coordinator) => <option key={coordinator.id} value={coordinator.id}>{coordinator.name}</option>)}</select></div>)}</div></Card></>}
    {tab === 'Schedule' && <Card className="operator-table-card"><h2>Tour schedule</h2><div className="resource-table"><div className="resource-row resource-head"><span>When</span><span>Service</span><span>Tour & customer</span><span>Provider</span><span>Location / status</span><span>Actions</span></div>{filteredSchedule.map((item) => <div className="resource-row" key={item.id}><strong>{formatDate(item.startTime)} · {new Date(item.startTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</strong><span>{item.title} · {item.type}</span><span>{item.destination} · {item.traveler.name}</span><span>{item.vendor?.name || 'Unassigned'}</span><span>{item.location} · {item.status}{item.bookingStatus ? ` / ${item.bookingStatus}` : ''}</span><Button onClick={() => openScheduleEdit(item)} type="button" variant="secondary">Edit</Button></div>)}{filteredSchedule.length === 0 && <p className="page-copy">No scheduled items match this search.</p>}</div></Card>}
    <Modal isOpen={formOpen} onClose={() => { setFormOpen(false); setEditingInventory(null) }} title={editingInventory ? 'Edit inventory item' : `Add ${tab.slice(0, -1)} inventory`}><div className="vendor-form"><label className="tp-input-wrap"><span className="tp-input-label">Provider</span><select className="tp-input" disabled={Boolean(editingInventory)} onChange={(event) => setForm({ ...form, vendorId: event.target.value })} value={form.vendorId}><option value="">Choose a vendor</option>{vendors.map((vendor) => <option key={vendor.id} value={vendor.id}>{vendor.name} · {vendor.category}</option>)}</select></label>{tab === 'Transport' && <label className="tp-input-wrap"><span className="tp-input-label">Transport type</span><select className="tp-input" onChange={(event) => setForm({ ...form, type: event.target.value as OperatorInventory['type'] })} value={form.type}><option value="FLIGHT">Flight</option><option value="TRANSFER">Ground transport / transfer</option></select></label>}<Input label="Service name" onChange={(event) => setForm({ ...form, title: event.target.value })} value={form.title} /><Input label="Location / route" onChange={(event) => setForm({ ...form, location: event.target.value })} value={form.location} /><Input label="Price (INR)" min="0" onChange={(event) => setForm({ ...form, price: event.target.value })} type="number" value={form.price} /><Input label="Availability" onChange={(event) => setForm({ ...form, availability: event.target.value })} value={form.availability} /><Input hint="Separate tags with commas" label="Interest tags" onChange={(event) => setForm({ ...form, tags: event.target.value })} value={form.tags} /><label className="tp-input-wrap"><span className="tp-input-label">Service details (JSON)</span><textarea className="tp-input resource-details" onChange={(event) => setForm({ ...form, details: event.target.value })} placeholder={tab === 'Hotels' ? '{"starRating":4,"roomTypes":["Deluxe","Suite"],"roomsAvailable":6}' : tab === 'Transport' ? '{"vehicle":"SUV","driver":"Name","capacity":6,"mode":"Cab"}' : '{"durationMinutes":120,"capacity":10,"provider":"Local guide"}'} value={form.details} /></label><Button disabled={Boolean(busyId)} onClick={() => void saveInventory()} type="button">{busyId === 'create' ? 'Saving…' : 'Save inventory'}</Button></div></Modal>
    <Modal isOpen={editing !== null} onClose={() => setEditing(null)} title="Update tour schedule"><div className="vendor-form"><Input label="Service name" onChange={(event) => setScheduleForm({ ...scheduleForm, title: event.target.value })} value={scheduleForm.title} /><Input label="Location" onChange={(event) => setScheduleForm({ ...scheduleForm, location: event.target.value })} value={scheduleForm.location} /><Input label="Start" onChange={(event) => setScheduleForm({ ...scheduleForm, startTime: event.target.value })} type="datetime-local" value={scheduleForm.startTime} /><Input label="End" onChange={(event) => setScheduleForm({ ...scheduleForm, endTime: event.target.value })} type="datetime-local" value={scheduleForm.endTime} /><Button disabled={Boolean(editing && busyId === editing.id)} onClick={() => void saveSchedule()} type="button">Save schedule</Button></div></Modal>
  </section></OperatorLayout>
}





