import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Button } from '../../components/Button'
import { Card } from '../../components/Card'
import { StatusBadge } from '../../components/StatusBadge'
import { OperatorLayout } from '../../layouts/OperatorLayout'
import { getOperatorTrips, subscribeToOperatorUpdates, type OperatorKpis, type OperatorTrip } from '../../services/operatorService'

const emptyKpis: OperatorKpis = { activeTours: 0, upcomingTours: 0, pendingBookings: 0, toursAtRisk: 0, issuesRequiringAction: 0, pendingApprovals: 0, totalRevenue: 0 }
export function OperatorDashboardPage() {
  const [trips, setTrips] = useState<OperatorTrip[]>([]); const [kpis, setKpis] = useState(emptyKpis); const [error, setError] = useState(''); const navigate = useNavigate()
  useEffect(() => { const load = () => { void getOperatorTrips().then(({ trips: nextTrips, kpis: nextKpis }) => { setTrips(nextTrips); setKpis(nextKpis) }).catch((reason) => setError(reason instanceof Error ? reason.message : 'Operations data is unavailable.')) }; load(); return subscribeToOperatorUpdates(load) }, [])
  const cards = [{ label: 'Active tours', value: kpis.activeTours.toString(), detail: 'Trips in progress', tone: 'primary' }, { label: 'Upcoming tours', value: kpis.upcomingTours.toString(), detail: 'Future confirmed journeys', tone: 'primary' }, { label: 'Pending bookings', value: kpis.pendingBookings.toString(), detail: 'Awaiting confirmation or payment', tone: 'warning' }, { label: 'Issues requiring action', value: kpis.issuesRequiringAction.toString(), detail: 'Disruptions, conflicts or budget risks', tone: 'danger' }, { label: 'Pending approvals', value: kpis.pendingApprovals.toString(), detail: 'Recovery plans awaiting action', tone: 'warning' }, { label: 'Revenue', value: `₹${kpis.totalRevenue.toLocaleString()}`, detail: 'Paid booking value', tone: 'success' }]
  const flagged = trips.filter((trip) => trip.riskLevel !== 'low')
  return <OperatorLayout><section className="operator-page"><header className="operator-page-heading"><div><p className="eyebrow">Command center</p><h1>Good morning, Operations.</h1><p>Here is where journeys need your attention right now.</p></div><span className="operator-live-dot">Live operations</span></header>{error && <p className="auth-error">{error}</p>}<section className="operator-kpis">{cards.map((kpi) => <Card className={`operator-kpi is-${kpi.tone}`} key={kpi.label}><span>{kpi.label}</span><strong>{kpi.value}</strong><small>{kpi.detail}</small></Card>)}</section><section className="operator-priority"><div className="operator-section-heading"><div><p className="eyebrow">Priority queue</p><h2>Priority Attention Required</h2></div><span>{flagged.length} flagged tours</span></div><div className="operator-flagged-list">{flagged.map((trip) => <Card className={`operator-flagged is-${trip.riskLevel}`} key={trip.id}><div className="operator-risk-marker" /><div className="operator-flagged-details"><div><span>{trip.id.slice(-8)}</span><StatusBadge status={trip.pendingApprovals ? 'pending' : 'at-risk'} /></div><h3>{trip.destination}</h3><p>{trip.traveler.name} · {trip.openDisruptions} disruption(s), {trip.pendingApprovals} plan(s) awaiting approval{trip.bookingProblems ? `, ${trip.bookingProblems} booking issue(s)` : ''}{trip.scheduleConflicts ? ', schedule conflict' : ''}</p></div><div className="operator-flagged-actions"><Button onClick={() => navigate('/operator/disruptions')} type="button" variant="secondary">View</Button><Button onClick={() => navigate('/operator/disruptions')} type="button">Resolve</Button></div></Card>)}{!flagged.length && <Card><p className="page-copy">No trips currently require operational attention.</p></Card>}</div></section></section></OperatorLayout>
}
