import { useEffect, useState } from 'react'
import { Card } from '../components/Card'
import { Input } from '../components/Input'
import { Button } from '../components/Button'
import { StatusBadge } from '../components/StatusBadge'
import { useAuth } from '../auth/AuthContext'
import { getVendors, type Vendor } from '../services/operatorService'
import { getVendorSlotRequests, submitVendorBid, type SlotRequest } from '../services/marketplaceService'

const label = (value: string) => value[0] + value.slice(1).toLowerCase()
export function VendorDashboardPage() {
  const { user } = useAuth(); const [vendor, setVendor] = useState<Vendor | null>(null); const [requests, setRequests] = useState<SlotRequest[]>([]); const [prices, setPrices] = useState<Record<string,string>>({}); const [notes, setNotes] = useState<Record<string,string>>({}); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [submitting, setSubmitting] = useState<string | null>(null)
  const load = async () => { try { setLoading(true); setError(''); const [vendors, nextRequests] = await Promise.all([getVendors(), getVendorSlotRequests()]); setVendor(vendors.find((candidate) => candidate.id === user?.vendorId) || null); setRequests(nextRequests) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load marketplace requests.') } finally { setLoading(false) } }
  useEffect(() => { if (user?.vendorId) void load() }, [user?.vendorId])
  const submit = async (request: SlotRequest) => { const price = Number(prices[request.id]); if (!Number.isFinite(price) || price <= 0) return setError('Enter a positive bid price.')
    try { setSubmitting(request.id); setError(''); await submitVendorBid(request.id, price, notes[request.id] || ''); setSuccess(`Bid submitted for ${request.destination}.`); await load() } catch (e) { setError(e instanceof Error ? e.message : 'Unable to submit bid.') } finally { setSubmitting(null) }
  }
  const responseTime = vendor ? `${vendor.responseTime}m` : '18m'; const confirmationRate = vendor ? `${Math.round(vendor.confirmationRate)}% confirmation rate` : '96% confirmation rate'
  return <section className="vendor-dashboard"><p className="eyebrow">Vendor portal</p><h1 className="page-title">Welcome back, {user?.name.split(' ')[0]}.</h1><p className="page-copy">Today’s partner inventory and marketplace opportunities.</p><div className="vendor-kpis"><Card><span>Open requests</span><strong>{requests.length}</strong><small>Matched to your category</small></Card><Card><span>Confirmed this week</span><strong>38</strong><small>{confirmationRate}</small></Card><Card><span>Response time</span><strong>{responseTime}</strong><small>Faster than partner average</small></Card></div>{error && <p className="auth-error" role="alert">{error}</p>}{success && <p className="auth-inline-message" role="status">{success}</p>}<Card className="vendor-request-list"><h2>Marketplace requests</h2>{loading && <p className="page-copy">Loading open requests…</p>}{!loading && requests.length === 0 && <p className="page-copy">No open requests currently match your category.</p>}{requests.map((request) => <div className="vendor-marketplace-request" key={request.id}><div className="vendor-marketplace-heading"><div><strong>{request.destination} · {label(request.category)}</strong><span>Needed {new Date(request.dateNeeded).toLocaleDateString()} · budget cap ₹{request.budgetCap.toLocaleString()}</span></div>{request.myBid && <StatusBadge status="pending" />}</div><div className="vendor-bid-form"><Input aria-label="Bid price" placeholder="Your price" type="number" min="1" value={prices[request.id] || ''} onChange={(e) => setPrices((current) => ({ ...current, [request.id]: e.target.value }))} /><Input aria-label="Bid note" placeholder="Note (optional)" value={notes[request.id] || ''} onChange={(e) => setNotes((current) => ({ ...current, [request.id]: e.target.value }))} /><Button disabled={submitting === request.id} onClick={() => void submit(request)} type="button">{submitting === request.id ? 'Submitting…' : request.myBid ? 'Update bid' : 'Place bid'}</Button></div>{request.myBid && <small className="page-copy">Current bid: ₹{request.myBid.price.toLocaleString()} · {request.myBid.notes || 'No note'}</small>}</div>)}</Card></section>
}
