import { useEffect, useState } from 'react'
import { Button } from '../../components/Button'
import { Card } from '../../components/Card'
import { AdminLayout } from '../../layouts/AdminLayout'
import { getPendingTripReviews, reviewTrip, type AdminReviewTrip } from '../../services/adminService'

export function AdminTripReviewsPage() {
  const [trips, setTrips] = useState<AdminReviewTrip[]>([]); const [selected, setSelected] = useState<string | null>(null); const [feedback, setFeedback] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const load = async () => { try { setError(''); const next = await getPendingTripReviews(); setTrips(next); setSelected(current => current && next.some(t=>t.id===current) ? current : next[0]?.id || null) } catch(e) { setError(e instanceof Error ? e.message : 'Unable to load trip reviews.') } }
  useEffect(()=>{ void load() },[])
  const trip = trips.find(t=>t.id===selected) || trips[0]
  const decide = async (decision:'APPROVE'|'REQUEST_CHANGES') => { if(!trip) return; setBusy(true); setError(''); try { await reviewTrip(trip.id,decision,feedback.trim()||undefined); setFeedback(''); await load() } catch(e) { setError(e instanceof Error ? e.message : 'Unable to review trip.') } finally { setBusy(false) } }
  return <AdminLayout><section className="operator-page"><header className="operator-page-heading"><div><p className="eyebrow">Trip approval</p><h1>Review finalized trips.</h1><p>Verify the traveler’s complete itinerary before payment is unlocked.</p></div><span>{trips.length} awaiting review</span></header>{error&&<p className="auth-error">{error}</p>}<div className="operator-disruption-grid"><section className="operator-plans"><div className="operator-section-heading"><h2>Approval queue</h2></div>{!trips.length&&<Card><p className="page-copy">No trips are waiting for approval.</p></Card>}{trips.map(item=><button key={item.id} className={`tp-option-card ${trip?.id===item.id?'is-selected':''}`} onClick={()=>setSelected(item.id)} type="button"><div><strong>{item.destination}</strong><span>{item.user.name} · {item.user.email}</span><small>{item.items.length} itinerary items · ₹{item.budget.toLocaleString()} budget</small></div><b>›</b></button>)}</section>{trip&&<Card><p className="eyebrow">Traveler</p><h2>{trip.user.name} · {trip.destination}</h2><p className="page-copy">{trip.origin||'Source not specified'} → {trip.destination} · {new Date(trip.startDate).toLocaleDateString()} – {new Date(trip.endDate).toLocaleDateString()} · {trip.travelerCount} traveler(s)</p><div className="wallet-table">{trip.items.map(item=><div className="wallet-line" key={item.id}><div><strong>{item.title}</strong><span>{item.type} · {item.location} · {new Date(item.startTime).toLocaleString()}</span></div><strong>₹{item.cost.toLocaleString()}</strong></div>)}</div><textarea className="tp-input mt-5" rows={4} value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="Approval note or recommended changes…"/><div className="flex gap-2 mt-4"><Button disabled={busy} onClick={()=>void decide('APPROVE')}>Approve trip</Button><Button disabled={busy} onClick={()=>void decide('REQUEST_CHANGES')} variant="secondary">Request changes</Button></div></Card>}</div></section></AdminLayout>
}
