import { useEffect, useState } from 'react'
import { Button } from '../../components/Button'
import { Card } from '../../components/Card'
import { SegmentedControl } from '../../components/SegmentedControl'
import { StatusBadge } from '../../components/StatusBadge'
import { subscribeToTripEvents } from '../../services/apiClient'
import { activeAffectedItem, activeTrip, approveRecovery, disruptTrip, getItinerary, notifyTripUpdated, recoveryDecisionModes, rejectRecovery, revertRecovery, type DecisionMode, type DisruptionResult, type RecoveryPlan } from '../../services/tripService'

const decisionModes = recoveryDecisionModes.map((id) => ({ id, label: id[0].toUpperCase() + id.slice(1) }))
type Decision = { planId: string; stage: 'pending-operator' | 'confirmed' }
export function DisruptionPage() {
  const [result, setResult] = useState<DisruptionResult | null>(null); const [mode, setMode] = useState<DecisionMode>('balanced'); const [decision, setDecision] = useState<Decision | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  useEffect(() => subscribeToTripEvents((event, payload) => {
    if (!payload.planId) return
    if (event === 'recovery-approved') setDecision((current) => { if (!current || current.planId !== payload.planId) return current; activeAffectedItem.clear(); notifyTripUpdated(); return { ...current, stage: 'confirmed' } })
    if (event === 'recovery-rejected') setDecision((current) => { if (current?.planId !== payload.planId) return current; setError('The operator rejected this recovery plan. Choose another option.'); return null })
  }), [])
  const simulate = async () => { const tripId = activeTrip.get(); if (!tripId) return setError('Create or generate a trip first.'); setLoading(true); setError(''); try { const items = await getItinerary(tripId); const flight = items.find((item) => item.type === 'FLIGHT') || items[0]; if (!flight) throw new Error('No itinerary item is available to simulate.'); const next = await disruptTrip(tripId, flight.id, 'delay', 'Flight delayed 90 minutes.', mode); activeAffectedItem.set(next.disruption.affectedItemId); setResult(next); setDecision(null); notifyTripUpdated() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to simulate disruption.') } finally { setLoading(false) } }
  const approve = async (plan: RecoveryPlan) => { try { await approveRecovery(plan.id); setDecision({ planId: plan.id, stage: 'pending-operator' }) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to approve recovery.') } }
  const reject = async (plan: RecoveryPlan) => { try { await rejectRecovery(plan.id); setResult((current) => current ? { ...current, disruption: { ...current.disruption, plans: current.disruption.plans.map((candidate) => candidate.id === plan.id ? { ...candidate, status: 'REJECTED' } : candidate) } } : current) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to reject recovery.') } }
  const revert = async (plan: RecoveryPlan) => { try { await revertRecovery(plan.id); setDecision(null); notifyTripUpdated() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to revert recovery.') } }
  return <section className="disruption-page"><header className="disruption-heading"><p className="eyebrow">Disruption adapt</p><h1 className="page-title">When plans move, you don’t have to.</h1><p className="page-copy">Simulate a 90-minute flight delay to run impact analysis and ranked recovery plans against verified inventory.</p></header><Button disabled={loading} onClick={() => void simulate()} type="button">{loading ? 'Analyzing disruption…' : 'Simulate Disruption'}</Button>{error && <p className="auth-error">{error}</p>}{decision?.stage === 'pending-operator' && <p className="auth-inline-message">Sent to the operator for approval. You’ll get a live update here once it’s confirmed.</p>}{result && <div className="disruption-results"><section><div className="disruption-section-heading"><p className="eyebrow">Impact analysis · {result.disruption.severity}</p><h2>{result.disruption.explanation}</h2></div><div className="affected-items">{result.disruption.affectedItems.map((item) => <Card className="affected-item" key={item.id}><div><strong>{item.title}</strong><span>{item.type} · Connected downstream impact</span></div><StatusBadge status="at-risk" /></Card>)}</div></section><section><div className="disruption-option-heading"><div><p className="eyebrow">Recovery options</p><h2>Three verified {result.disruption.decisionMode} recovery strategies.</h2></div><SegmentedControl onChange={(value) => setMode(value as DecisionMode)} options={decisionModes} value={mode} /></div><div className="recovery-options">{result.disruption.plans.map((plan, index) => <Card className={`recovery-option ${decision?.planId === plan.id ? 'is-approved' : ''}`} key={plan.id}><span className="recovery-rank">#{index + 1} · {plan.finalScore} score</span><h3>{index === 0 ? 'Best deterministic match' : index === 1 ? 'Balanced alternative' : 'Verified fallback'}</h3><p>{plan.explanation}</p><span className="change-impact">{plan.extraCost >= 0 ? '+' : ''}₹{plan.extraCost.toLocaleString()} · +{plan.timeDelta} min · {plan.preferenceScore}% match · {plan.vendorReliability}% reliable</span><div className="recovery-actions"><Button disabled={plan.status === 'REJECTED' || decision !== null} onClick={() => void approve(plan)} type="button">{decision?.planId === plan.id ? (decision.stage === 'confirmed' ? 'Approved' : 'Awaiting operator…') : 'Approve'}</Button><Button disabled={plan.status === 'REJECTED' || decision !== null} onClick={() => void reject(plan)} type="button" variant="secondary">Reject</Button><Button disabled={decision?.planId !== plan.id || decision?.stage !== 'confirmed'} onClick={() => void revert(plan)} type="button" variant="ghost">Revert</Button></div></Card>)}</div></section></div>}</section>
}
