import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { Button } from '../../components/Button'
import { Card } from '../../components/Card'
import { ChipSelector } from '../../components/ChipSelector'
import { Input } from '../../components/Input'
import { SegmentedControl } from '../../components/SegmentedControl'
import { Slider } from '../../components/Slider'
import { useAuth } from '../../auth/AuthContext'
import { createTrip } from '../../services/tripService'
import { discoverDestination, type PlaceItem } from '../../services/travelDiscoveryService'
import { destinationImage } from '../../lib/destinationImages'

const interestIds = ['adventure', 'food', 'culture', 'nightlife', 'relaxation', 'familyFriendly']
const travelStyleIds = ['solo', 'couple', 'family', 'group']
const tripTypeIds = ['leisure', 'adventure', 'cultural', 'business', 'wellness']
const fallbackImageFor = (index: number) => `https://images.unsplash.com/photo-${['1500530855697-b586d89ba3ee','1524492412937-b28074a5d7da','1530789253388-582c481c54b0'][index % 3]}?auto=format&fit=crop&w=900&q=80`
function savedPackage() { try { return JSON.parse(sessionStorage.getItem('voyara-selected-package') || 'null') as { destination?: string; price?: number } | null } catch { return null } }

export function OnboardingPage() {
  const navigate = useNavigate(); const { completeOnboarding } = useAuth()
  const { t } = useTranslation()
  const interestChips = interestIds.map((id) => ({ id, label: t(`onboarding.interests.${id}`) }))
  const travelStyles = travelStyleIds.map((id) => ({ id, label: t(`onboarding.travelStyles.${id}`) }))
  const tripTypes = tripTypeIds.map((id) => ({ id, label: t(`onboarding.tripTypes.${id}`) }))
  const formatPrice = (price: PlaceItem['price']) => { if (price.amount === null) return null; if (price.amount === 0) return t('onboarding.free'); const formatted = price.currency === 'INR' ? `₹${price.amount.toLocaleString('en-IN')}` : `${price.amount.toLocaleString()} ${price.currency}`; return price.status === 'CURATED' || price.status === 'ESTIMATED' ? `~${formatted}` : formatted }
  const [step, setStep] = useState(0)
  const [form, setForm] = useState(() => { const preset = savedPackage(); return { origin: '', destination: preset?.destination || '', departureDate: '', returnDate: '', travelers: 1, budget: preset?.price || 25000, interests: [] as string[], pace: 50, travelStyle: 'solo', tripType: 'leisure', selectedPlaces: [] as string[], selectedActivities: [] as string[], selectedDays: {} as Record<string,string> } })
  const [discovery, setDiscovery] = useState<{ places: PlaceItem[]; activities: PlaceItem[] } | null>(null)
  const [loadingDiscovery, setLoadingDiscovery] = useState(false); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState('')
  const days = Math.max(1, Math.ceil((new Date(form.returnDate).getTime() - new Date(form.departureDate).getTime()) / 86400000))
  const update = <K extends keyof typeof form>(key: K, value: typeof form[K]) => setForm((current) => ({ ...current, [key]: value }))
  const setTravelStyle = (style: string) => setForm((current) => ({ ...current, travelStyle: style, travelers: style === 'solo' ? 1 : style === 'couple' ? 2 : current.travelers < 3 ? 3 : current.travelers }))
  const toggle = (key: 'selectedPlaces'|'selectedActivities', id: string) => update(key, form[key].includes(id) ? form[key].filter((x) => x !== id) : [...form[key], id])
  const validate = () => { if (!form.origin.trim()) return t('onboarding.enterOrigin'); if (!form.destination.trim()) return t('onboarding.enterDestination'); if (!form.departureDate || !form.returnDate) return t('onboarding.selectDates'); if (new Date(form.returnDate) <= new Date(form.departureDate)) return t('onboarding.returnAfter'); if (form.travelers < 1) return t('onboarding.atLeastOneTraveler'); if (form.budget <= 0) return t('onboarding.validBudget'); return '' }
  const loadDiscovery = async () => { const message = validate(); if (message) { setError(message); return }; setError(''); setLoadingDiscovery(true); try { const result = await discoverDestination({ destination: form.destination, origin: form.origin, checkIn: form.departureDate, checkOut: form.returnDate, travelers: form.travelers, budget: form.budget, interests: form.interests, tripStyle: form.travelStyle }); setDiscovery({ places: result.places, activities: result.activities }); setStep(1) } catch (e) { setError(e instanceof Error ? e.message : t('onboarding.unableToLoadOptions')) } finally { setLoadingDiscovery(false) } }
  const submit = async () => { const message = validate(); if (message) { setError(message); setStep(0); return }; setSubmitting(true); setError(''); try { await createTrip({ origin: form.origin, destination: form.destination, startDate: new Date(form.departureDate).toISOString(), endDate: new Date(form.returnDate).toISOString(), budget: form.budget, travelerCount: form.travelers, tripType: form.tripType, travelStyle: form.travelStyle, interests: form.interests, pace: form.pace, status: 'DRAFT', requestedPlaces: form.selectedPlaces, requestedActivities: form.selectedActivities, requestedActivityDays: form.selectedDays }); sessionStorage.removeItem('voyara-selected-package'); completeOnboarding(); navigate('/traveler/composer', { state: { autoGenerate: true } }) } catch (e) { setError(e instanceof Error ? e.message : t('onboarding.unableToSaveTrip')) } finally { setSubmitting(false) } }
  const optionCard = (item: PlaceItem, selected: boolean, onClick: () => void, index: number) => { const price = formatPrice(item.price); return <button className={`tp-option-card ${selected ? 'is-selected' : ''}`} onClick={onClick} type="button"><img alt={`${item.name}, ${form.destination}`} loading="lazy" src={item.image || destinationImage(form.destination,index) || fallbackImageFor(index)} /><div><strong>{item.name}</strong><span>{item.type} · {item.estimatedVisitDuration || t('onboarding.flexibleDuration')}</span><small>{item.address || item.description || t('onboarding.discoveryResult')}</small>{price && <small className="tp-option-price">{price}{item.price.status === 'CURATED' && ` · ${t('onboarding.estimated')}`}</small>}</div><b>{selected ? '✓' : '+'}</b></button> }
  return <section className="onboarding-page"><div className="onboarding-intro"><p className="eyebrow">{t('onboarding.eyebrow')}</p><h1 className="page-title">{t('onboarding.title')}</h1><p className="page-copy">{t('onboarding.copy')}</p></div>
    <Card className="onboarding-card"><ol className="onboarding-progress" aria-label="Trip planning progress">{(t('onboarding.steps', { returnObjects: true }) as string[]).map((label,i)=><li className={i<=step?'is-current':''} key={label}><span>{i+1}</span><strong>{label}</strong></li>)}</ol>
      {step===0 && <div className="onboarding-step"><h2>{t('onboarding.whereGoing')}</h2><p>{t('onboarding.whereGoingCopy')}</p><div className="onboarding-field-grid"><Input label={t('onboarding.from')} value={form.origin} onChange={e=>update('origin',e.target.value)} placeholder="Mumbai" required/><Input label={t('onboarding.to')} value={form.destination} onChange={e=>update('destination',e.target.value)} placeholder="Goa" required/></div>{destinationImage(form.destination) && <div className="onboarding-destination-preview"><img alt={`${form.destination} destination inspiration`} src={destinationImage(form.destination)!}/><span>{t('onboarding.destinationInspiration')} · {form.destination}</span></div>}<div className="onboarding-field-grid"><Input label={t('onboarding.startDate')} type="date" value={form.departureDate} onChange={e=>update('departureDate',e.target.value)} required/><Input label={t('onboarding.endDate')} type="date" value={form.returnDate} onChange={e=>update('returnDate',e.target.value)} required/></div><Button disabled={loadingDiscovery} onClick={()=>void loadDiscovery()} type="button">{loadingDiscovery?t('onboarding.findingPlaces'):t('onboarding.findPlacesActivities')}</Button></div>}
      {step===1 && <div className="onboarding-step"><div className="flex items-center justify-between gap-4"><div><h2>{t('onboarding.whatToDo')}</h2><p>{t('onboarding.whatToDoCopy')}</p></div><Button variant="ghost" onClick={()=>setStep(0)}>{t('onboarding.changeDestination')}</Button></div><div className="tp-option-grid">{(discovery?.places||[]).slice(0,12).map((item,i)=>optionCard(item,form.selectedPlaces.includes(item.name),()=>toggle('selectedPlaces',item.name),i))}</div><h3 className="mt-6">{t('onboarding.activitiesExperiences')}</h3><div className="tp-option-grid">{(discovery?.activities||[]).slice(0,12).map((item,i)=>optionCard(item,form.selectedActivities.includes(item.name),()=>toggle('selectedActivities',item.name),i+12))}</div><div className="mt-6"><strong>{t('onboarding.optionalAssignDay')}</strong>{[...form.selectedPlaces,...form.selectedActivities].map(name=><div className="flex items-center gap-3 mt-3" key={name}><span className="page-copy" style={{minWidth:220}}>{name}</span><select className="tp-input" value={form.selectedDays[name]||''} onChange={e=>setForm(x=>({...x,selectedDays:{...x.selectedDays,[name]:e.target.value}}))}><option value="">{t('onboarding.anyDayVoyaraDecides')}</option>{Array.from({length:days},(_,i)=><option key={i+1} value={String(i+1)}>{t('onboarding.day')} {i+1}</option>)}</select></div>)}</div><div className="onboarding-actions"><Button variant="ghost" onClick={()=>setStep(0)}>{t('onboarding.back')}</Button><Button onClick={()=>setStep(2)}>{t('onboarding.continue')}</Button></div></div>}
      {step===2 && <div className="onboarding-step"><h2>{t('onboarding.whoIsThisFor')}</h2><p>{t('onboarding.whoIsThisForCopy')}</p><div className="onboarding-style"><span>{t('onboarding.travelStyle')}</span><SegmentedControl options={travelStyles} value={form.travelStyle} onChange={setTravelStyle}/></div><div className="onboarding-style"><span>{t('onboarding.numberOfTravellers')}</span><Input label="" type="number" min="1" max="100" value={form.travelers} disabled={form.travelStyle==='solo'||form.travelStyle==='couple'} onChange={e=>update('travelers',Math.max(1,Number(e.target.value)))} /></div><div className="onboarding-style"><span>{t('onboarding.tripType')}</span><SegmentedControl options={tripTypes} value={form.tripType} onChange={v=>update('tripType',v)}/></div><div className="onboarding-slider-value">₹{form.budget.toLocaleString()}</div><Slider label={t('onboarding.totalBudget')} max="1000000" min="1000" step="1000" value={form.budget} onChange={e=>update('budget',Number(e.target.value))}/><div className="onboarding-actions"><Button variant="ghost" onClick={()=>setStep(1)}>{t('onboarding.back')}</Button><Button onClick={()=>setStep(3)}>{t('onboarding.continue')}</Button></div></div>}
      {step===3 && <div className="onboarding-step"><h2>{t('onboarding.setYourRhythm')}</h2><p>{t('onboarding.setYourRhythmCopy')}</p><ChipSelector chips={interestChips} selected={form.interests} onChange={id=>update('interests',form.interests.includes(id)?form.interests.filter(x=>x!==id):[...form.interests,id])}/><div className="onboarding-slider-value">{form.pace<34?t('onboarding.relaxed'):form.pace>66?t('onboarding.packed'):t('onboarding.balanced')}</div><Slider label={t('onboarding.travelPace')} max="100" min="0" value={form.pace} onChange={e=>update('pace',Number(e.target.value))}/><p className="page-copy">{form.selectedPlaces.length+form.selectedActivities.length===0?t('onboarding.noFixedSelections'):t('onboarding.itemsPrioritized', { count: form.selectedPlaces.length+form.selectedActivities.length })}</p>{error&&<p className="auth-error">{error}</p>}<div className="onboarding-actions"><Button variant="ghost" onClick={()=>setStep(2)}>{t('onboarding.back')}</Button><Button disabled={submitting} onClick={()=>void submit()}>{submitting?t('onboarding.creating'):t('onboarding.createMyTrip')}</Button></div></div>}
      {error && step!==3 && <p className="auth-error" role="alert">{error}</p>}
    </Card></section>
}
