import { useEffect, useState } from 'react'
import { Button } from '../../components/Button'
import { Card } from '../../components/Card'
import { Slider } from '../../components/Slider'
import { Tabs } from '../../components/Tabs'
import { activeTrip, applySimulation, notifyTripUpdated, simulateTrip, type TripSimulation } from '../../services/tripService'

const tiers = [{ id: 'standard', label: 'Current tier' }, { id: 'cheaper', label: 'Cheaper stay' }, { id: 'premium', label: 'Premium stay' }]
export function SimulatorPage() {
  const [budgetDelta, setBudgetDelta] = useState(10000); const [tier, setTier] = useState('standard'); const [preview, setPreview] = useState<TripSimulation | null>(null); const [loading, setLoading] = useState(false); const [applying, setApplying] = useState(false); const [error, setError] = useState(''); const tripId = activeTrip.get()
  useEffect(() => { if (!tripId) return; const timeout = window.setTimeout(() => { setLoading(true); void simulateTrip(tripId, { budgetDelta, hotelTier: tier === 'standard' ? undefined : tier as 'cheaper' | 'premium' }).then(setPreview).catch((reason) => setError(reason instanceof Error ? reason.message : 'Unable to create simulation preview.')).finally(() => setLoading(false)) }, 450); return () => window.clearTimeout(timeout) }, [budgetDelta, tier, tripId])
  const apply = async () => { if (!tripId || !preview) return; try { setApplying(true); await applySimulation(tripId, preview.simulationId); notifyTripUpdated(); setPreview(null) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to apply simulation.') } finally { setApplying(false) } }
  return <section className="wallet-page"><div className="wallet-heading"><p className="eyebrow">What-if simulator</p><h1 className="page-title">Try the trade-off before you take it.</h1><p className="page-copy">This preview never changes your trip until you explicitly apply it.</p></div>{error && <p className="auth-error">{error}</p>}<div className="wallet-overview"><Card className="wallet-stats"><h2>Hypothetical changes</h2><Slider label={`Budget change: ${budgetDelta >= 0 ? '+' : ''}₹${budgetDelta.toLocaleString()}`} max={20000} min={-20000} onChange={(event) => setBudgetDelta(Number(event.target.value))} step={1000} value={budgetDelta} /><Tabs activeId={tier} onChange={setTier} tabs={tiers} /><p className="page-copy">Preview refreshes shortly after each slider change.</p></Card><Card className="wallet-stats"><h2>Budget impact</h2><div className="wallet-stat"><span>Before</span><strong>₹{(preview?.currentCost || 0).toLocaleString()}</strong></div><div className="wallet-stat"><span>After</span><strong>₹{(preview?.simulatedCost || 0).toLocaleString()}</strong></div><div className="wallet-stat"><span>Delta</span><strong>{preview ? `${preview.costDelta >= 0 ? '+' : ''}₹${preview.costDelta.toLocaleString()}` : '—'}</strong></div><div className="wallet-stat"><span>Remaining</span><strong>{preview ? `₹${preview.budgetImpact.remaining.toLocaleString()}` : '—'}</strong></div><div className="wallet-stat"><span>Carbon impact</span><strong>{preview ? `${preview.carbonDeltaKg && preview.carbonDeltaKg >= 0 ? '+' : ''}${(preview.carbonDeltaKg || 0).toFixed(1)} kg CO₂` : '—'}</strong></div></Card></div><Card className="wallet-line-items"><div className="wallet-line-heading"><div><p className="eyebrow">Before vs after</p><h2>{loading ? 'Calculating preview…' : `${preview?.changes.length || 0} real itinerary change(s)`}</h2></div>{preview && <Button disabled={applying} onClick={() => void apply()} type="button">{applying ? 'Applying…' : 'Apply this simulation'}</Button>}</div><div className="wallet-table">{preview?.currentItinerary.map((item, index) => { const next = preview.simulatedItinerary[index]; const changed = item.title !== next?.title || item.cost !== next?.cost; return <div className="wallet-line" key={item.id}><div><strong>BEFORE · {item.title}</strong><span>₹{item.cost.toLocaleString()} · {item.location}</span></div><div><strong>AFTER · {next?.title || item.title}</strong><span>₹{(next?.cost || item.cost).toLocaleString()} · {next?.location || item.location}{changed ? ' · changed' : ''}</span></div></div> })}</div>{preview && <p className="page-copy">Time delta: {preview.timeDelta >= 0 ? '+' : ''}{preview.timeDelta} min · Preference score delta: {preview.preferenceScoreDelta >= 0 ? '+' : ''}{preview.preferenceScoreDelta} · {preview.budgetImpact.overflow ? 'Budget exceeded' : 'Within simulated budget'}</p>}</Card></section>
}
